apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler-secretstore
  namespace: external-secrets-operator
spec:
  provider:
    doppler:
      auth:
        # Assuming DOPPLER_TOKEN is set as a Kubernetes Secret in the external-secrets-operator namespace
        secretRef:
          name: doppler-auth
          key: token
      # Optional: specify a project and config if not using default
      # project: "your-doppler-project"
      # config: "your-doppler-config"

