apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: databases
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fatoh2/argus-infra
    targetRevision: main
    path: k8s/databases
  destination:
    server: https://kubernetes.default.svc
    namespace: databases # Target namespace for database applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
