apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      version: "0.9.x"
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    installCRDs: true
    serviceAccount:
      create: true
      name: external-secrets-sa
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
