apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-root
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/argocd/apps
    repoURL: https://github.com/fatoh2/argus-infra # NOTE: Hardcoded for initial setup. Consider templating for advanced use cases.
    targetRevision: HEAD # NOTE: Ensure robust CI/CD practices for the main branch as changes will be automatically synced.
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
