apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - default-deny-all.yaml
  - allow-api-to-postgres.yaml
  - allow-api-to-redis.yaml
  - allow-solana-adapter-egress.yaml
  - allow-ingress-to-api.yaml
