---
- name: Resolve k3s server host in k3s_server group
  ansible.builtin.set_fact:
    k3s_server_host: "{{ groups['k3s_server'][0] }}"

- name: Download k3s install script
  ansible.builtin.get_url:
    url: "{{ k3s_install_url }}"
    dest: /tmp/k3s-install.sh
    mode: "0700"
    force: false

- name: Install k3s agent  # noqa: command-instead-of-shell
  ansible.builtin.shell:
    cmd: /tmp/k3s-install.sh
    creates: /usr/local/bin/k3s
  environment:
    INSTALL_K3S_EXEC: "agent"
    INSTALL_K3S_VERSION: "{{ k3s_version | default('', true) }}"
    K3S_URL: "https://{{ hostvars[k3s_server_host]['ansible_host'] }}:6443"
    K3S_TOKEN: "{{ hostvars[k3s_server_host]['k3s_node_token'] }}"
  no_log: true
  notify: Restart k3s-agent

- name: Enable and start k3s-agent service
  ansible.builtin.systemd:
    name: k3s-agent
    enabled: true
    state: started
    daemon_reload: true

- name: Wait for k3s-agent service to be active
  ansible.builtin.systemd:
    name: k3s-agent
  register: k3s_agent_service_status
  until: k3s_agent_service_status.status.ActiveState == "active"
  retries: 20
  delay: 5
